// cotizador-vite/cotizador-vue/src/App.vue
<script setup>
import { ref ,computed, watch} from "vue";
import Header from "./components/Header.vue";
import Button from "./components/Button.vue";
import { calcularTotalApagar } from "./helpers";

const cantidad = ref(0);
const meses = ref(0)
const MIN = 0
const total = ref(0);
const MAX = 20000
const STEP =178.96



// Metodo 
const formatearDinero = (valor)=>{
    const formatear = new Intl.NumberFormat('en-US',{
        style: 'currency',
        currency:'USD'
    });

    return formatear.format(valor)
};


//function  vue.js 

watch([cantidad, meses],()=>{
    total.value = calcularTotalApagar (cantidad.value, meses.value);
})


const pagoMensual = computed(()=>{
    return total.value / meses.value
});


const handleChangeDecremento = ()=>{
    const valor = cantidad.value - STEP;

    if (valor < MIN) {
        alert('Cantidad Ivalida');
        return;
    }
       
    cantidad.value = valor;

}



const handleChangeIncremento = ()=>{
    const valor = cantidad.value + STEP;

    if (valor > MAX) {
        alert('Cantidad Ivalida');
        return;
    }

    cantidad.value = valor;
}


</script>





<template>
    
    <div class="my-20 max-w-lg mx-auto bg-white shad p-10">
        <Header/>
        
        <div class="flex justify-between mt-10">
            <Button 
            :operador="'-'"
            @fn="handleChangeDecremento"
            /> 

            <Button 
            :operador="'+'"
            @fn="handleChangeIncremento"
            /> 


        </div>
        


        <div class="my-5">

            <input
             type="range"
             class=" w-full bg-gray-200 accent-lime-600 hover:accent-lime-700"
             :min=" MIN "
             :max=" MAX "
             :step="STEP "
            v-model.number="cantidad"

            />

            <p class="text-center my-10 text-5xl font-extrabold text-indigo-600">
                 {{ formatearDinero(cantidad) }}
            </p>

            <h2 class="text-2xl font-extrabold text-gray-500 text-center">

                ELige un <span class=" text-indigo-700 ">Plazo </span> a pagar 

            </h2>

            <select class="w-full p-2 bg border-gray-300 rounded-lg text-center text-xl font-bold text-gray-800 mt-5" 
            v-model.nu="meses"
            >

                <option value="0" disabled selected>Selecciona Meses de pago</option>
                <option value="6">6 Meses</option>
                <option value="12">12 Meses</option>
                <option value="16">16 Meses</option>
                <option value="22">22 Meses</option>
            </select>
        </div>

<div  v-if="total > 0" class= " my-5 space-y-3 bg-gray-50 p-5">
    <h2 class="text-2xl font-extrabold text-gray-500 text-center">
        Resumen <span class="text-indigo-600">de pagos</span>
    </h2>

    <p class="text-xl text-gray-500 font-bold"> {{meses}} Meses </p>
    <p class="text-xl text-gray-800 font-bold"> Total a Pagar: {{ formatearDinero(total) }}</p>
    <p class="text-xl text-gray-500 font-bold">Mensuales: {{formatearDinero(pagoMensual)}}  </p>

</div>

    <p v-else class="text-center">selecciona el plazo a pagar.</p>

</div>
</template>

// cotizador-credito-react/cotizador-prestamos-react/src/App.jsx
import { useState,useEffect } from "react";
import  Header  from "./components/Header";
import Button from "./components/Button";
import { formatearDinero,calcularTotalPagar } from "./helpers";


function App() {
  const [cantidad, setcantidad] = useState(10000);
  const [meses,setMeses] = useState(6);
  const [total,setTotal] = useState(calcularTotalPagar(cantidad,meses))
  const [pago,setPago] = useState(0)

// useEffect-------------------------------------------------

    useEffect(()=>{
      const resultadoTotalPagar = calcularTotalPagar(cantidad,meses);
      setTotal(resultadoTotalPagar); 
      },[cantidad,meses])

    useEffect(()=>{
    // Calcular el pago mensual 
    setPago(total/meses)
    },[total])

// State cantidad-------------------------------------------------

  const MIN = 0;
  const MAX = 20000;
  const STEP = 100;


  function handleChange(e) {
    setcantidad(parseInt(e.target.value));
    
  }    

  function handleClickDecrement() {
    const valor = cantidad - STEP;
  
    if (valor < MIN) {
      alert('Invalid Amount');
      return;
    } 

    setcantidad(valor)
  }

  function handleClickIncrement() {
    const valor = cantidad + STEP;
  
    if (valor > MAX) {
      alert('Invalid Amount');
      return;
    } 

    setcantidad(valor)
  }

  return (

    <div className="my-20 max-w-lg mx-auto bg-white shadow p-10">
      {/* {} - indica que tiene que ir la var que deseamos agregar  */}
      {/* se puede usar el operador ? ternario isntead if else */}

    <Header />

      <div className="flex justify-between my-4"> 
        <Button 
          operador="-"
          fn={handleClickDecrement}
        />
        <Button 
          operador="+"
          fn={handleClickIncrement}
        />


      </div>



      <input 
          type="range" 
          className="w-full h-6 bg-gray-200 accent-lime-500 hover:accent-lime-600 "
          onChange={handleChange}

        min={MIN}
        max={MAX}
        step={STEP}
        value={cantidad}

      />

      <p className="text-center my-10 text-5xl font-extrabold text-indigo-700">
        {formatearDinero(cantidad)}
      </p>

      <h2 className="text-2xl font-extrabold text-gray-500 text-center">
        Elige un <span className=" text-indigo-600">plazo</span> a pagar
      </h2>

      <select className="mt-5 w-full p-2 bg-white border border-gray-300 rounded-lg text-center text-xl font-bold" 
      value={meses}


      // State Meses-------------------------------------------------

      onChange={e => setMeses(parseInt(e.target.value))}
      >
        <option value="6"> 6 Meses</option>
        <option value="12">12 Meses</option>
        <option value="18">18 Meses</option>
        <option value="24">24 Meses</option>
      </select>


      <div className="my-5 space-y-3 bg-gray-50 p-5">
        <h2 className="text-2xl font-extrabold text-gray-500 text-center">
          Resumen <span className=" text-indigo-600">de pagos</span> 
        </h2>
      </div>
        
      <p className=" text-xl text-gray-500 text-center font-bold ">{meses} Meses</p>
      <p className=" text-xl text-gray-500 text-center font-bold ">{formatearDinero(total)} Total a Pagar</p>
      <p className=" text-xl text-gray-500 text-center font-bold ">{formatearDinero(pago)} Mensuales</p>

    </div>

    )
}

export default App
